Replace termcolor with colored module
marcusbuffett/command-line-chess pull request #40
Opened 2022-10-03 16:21 UTC by GauthamBellamkonda

Fixes #37 

Add new option to the CLI for checkered board
Use colored module for printing the board
Update README

2022-10-03 17:22 UTC, ClasherKasten requested changes
Unfortunately there are several problems with this implementation:
- when using `chess -c`, the pieces don't get printed in the center of the square
![cl-chess_bug#40](https://user-images.githubusercontent.com/94523763/193639150-5a3ac012-9ac6-4715-8179-581e221b1bf8.png)
- when using `chess -cu` some parts of the board don't get printed at all
![cl-chess_bug#40 1](https://user-images.githubusercontent.com/94523763/193639381-88b3fddd-0c86-48f6-b92b-68a236f51d59.png)

2022-10-04 05:20 UTC, GauthamBellamkonda commented
I'm not able to reproduce the second bug. Using ```chess -cu``` prints a complete board on my machine. I'm using the standard terminal on Ubuntu 20.04.

![image](https://user-images.githubusercontent.com/73273020/193734753-ac318ade-2260-4cba-983e-41b11e740b9b.png)

For the first bug, we could use full width unicode characters (they basically occupy twice the width of a normal character) to represent pieces on the board. I had to 
 - replace the triangle character '▲' for a pawn with a full-width 'p', and 
 - replace the full stop characters with a space for empty cells. 
  
It finally looks like this

![image](https://user-images.githubusercontent.com/73273020/193740307-fa05554d-69e2-4f1d-a340-2657bbf3d00d.png)

Let me know if this is good enough, or if you have any better ideas/proposals.

2022-10-07 15:21 UTC, ClasherKasten commented
> I'm not able to reproduce the second bug. Using chess -cu prints a complete board on my machine. I'm using the standard terminal on Ubuntu 20.04.

Interestingly I couldn't reproduce it myself. Don't know what exactly this was, but let's say it's non-existing for now.

> For the first bug, we could use full width unicode characters (they basically occupy twice the width of a normal character) to represent pieces on the board.

The whole idea of a separated unicode mode was to also let people play this when their terminal has no proper unicode support.
So it wouldn't make any sense replacing the normal characters through unicode characters.
I think it is almost impossible to achieve a good looking result without unicode characters.

The plan I have now in mind would be to remove the `-u` switch and fully convert the application to unicode only.
I'll open a new issue for removing non-unicode mode.


But before I merge this, it would be nice to switch out the dependencies in the `requirements.txt` and `setup.py` files

2022-10-07 19:03 UTC, ClasherKasten approved these changes

2022-10-07 19:04 UTC, merged